.circleci/config.yml
README.md
package.json

Add some NPM scripts so commands are easier to understand.
P/S: I'm gonna start spamming you with PRs so you guys can get familiar/comment on library code/setup.

Streamline npm scripts

---

.circleci/config.yml
package-lock.json
package.json
packages/_bootstrap_/package.json
packages/_storybook_/package.json
packages/button/Button.vue
packages/button/package.json

- Add Husky to manage git hooks (https://github.com/typicode/husky)
- Streamline some commands and ci commands
- Run linting and tests on a pre-commit hook
- Add NPM access config to packages.json

Add Husky to manage git hooks

---

commitlint.config.js
package-lock.json
package.json

The commitlint tool checks that the commit message format for conventional commits is ok.
Conventional commits allow us to automate:
- Package versioning
- Changelog generation
To know more about [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)

Add commitlint check in a commit-message hook

---

packages/_bootstrap_/scss/colors.scss

https://reciprocitylabs.atlassian.net/browse/ZEN-10057
New brown color added for statuses.

ZEN-10057: Add new color for statuses

---

packages/_bootstrap_/scss/variables.scss

Finishing https://github.com/reciprocity/zenlib/pull/15 :)

QUICK-FIX: Add new color to status mapping

---

packages/_storybook_/package-lock.json
packages/_storybook_/package.json

Adds missing dependency to the storybook package.

Add loading-spinner as a storybook dependency

---

.circleci/config.yml
packages/day-selector/DaySelector.spec.js
packages/day-selector/DaySelector.vue
packages/day-selector/README.md
packages/day-selector/index.js
packages/day-selector/package-lock.json
packages/day-selector/package.json

Copy DaySelector component from ZenGRC to the component library.

ZEN-10019: Add new DaySelector component

---

packages/_storybook_/.storybook/config.js
packages/_storybook_/package-lock.json
packages/_storybook_/package.json
packages/_storybook_/stories/Button.stories.js
packages/_storybook_/stories/DaySelector.stories.js

- Add DaySelector story to storybook
- Move `withPadding` decorator to a global place.

Add DaySelector story to storybook

---

.circleci/config.yml
bundlesize.config.json
package-lock.json
package.json

Adding this `bundlesize` tool to have as a safeguard that we're not including a super heavy library in any component.

Add bundle size checks

---

packages/file-dropzone/FileDropzone.spec.js
packages/file-dropzone/FileDropzone.vue
packages/file-dropzone/README.md
packages/file-dropzone/index.js
packages/file-dropzone/package-lock.json
packages/file-dropzone/package.json

[JIRA Ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-10020)

ZEN-10020: Add FileDropzone component

---

packages/multiselect/Multiselect.vue

[ZEN-11024](https://reciprocitylabs.atlassian.net/browse/ZEN-11024)

ZEN-11024: Change multiselect tag close button

---

packages/_bootstrap_/scss/custom.scss
packages/_bootstrap_/scss/overrides.scss

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-8629)
As per JIRA ticket
Changes were also made on focus states of inputs, so that states match (validated / not validated).

ZEN-8629: Validation on text fields

---

package-lock.json

```
➜ npm audit
=== npm audit security report ===                        
found 0 vulnerabilities
in 1801574 scanned packages
```

Fix dependencies security issues

---

packages/_storybook_/package-lock.json
packages/_storybook_/package.json
packages/_storybook_/stories/ColorPicker.stories.js
packages/color-input/ColorInput.vue
packages/color-input/package-lock.json
packages/color-input/package.json
packages/color-picker/package-lock.json
packages/color-picker/package.json
rollup.config.js

Connect the newly created [color picker package](https://www.npmjs.com/package/@reciprocity/color-picker) with stories and ColorInput component.

QUICK-FIX: Connect color picker with the newly created package

---

.circleci/config.yml
package.json
packages/_storybook_/package-lock.json
packages/_storybook_/package.json

[JIRA Ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-11142)

ZEN-11142: Add build and deploy workflow for the storybook website

---

packages/_storybook_/.storybook/addons.js
packages/_storybook_/.storybook/config.js
packages/_storybook_/package-lock.json
packages/_storybook_/package.json
packages/_storybook_/stories/Button.stories.js
packages/_storybook_/stories/ColorInput.stories.js
packages/_storybook_/stories/ColorPicker.stories.js
packages/_storybook_/stories/DaySelector.stories.js
packages/_storybook_/stories/LoadingSpinner.stories.js
packages/_storybook_/stories/Multiselect.stories.js
packages/color-input/README.md
packages/day-selector/README.md
packages/loading-spinner/README.md

[JIRA ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-11146)
Adding and configuring the `storybook-readme` addon.

ZEN-11146: Add components READMEs to storybook

---

packages/color-input/ColorInput.vue

I changed the export of a component just to test the slack notification.

Change color input export

---

.circleci/config.yml

Making the slack notification work

git pull before calling slack-message.js

---

packages/color-picker/ColorPicker.vue

Just a small change, to trigger a slack message

Update color pickers export

---

.gitignore
packages/_storybook_/package.json
packages/_storybook_/stories/DropdownMultiselect.stories.js
packages/dropdown-multiselect/DropdownMultiselect.spec.js
packages/dropdown-multiselect/DropdownMultiselect.vue
packages/dropdown-multiselect/README.md
packages/dropdown-multiselect/index.js
packages/dropdown-multiselect/package-lock.json
packages/dropdown-multiselect/package.json

Duplicate of https://github.com/reciprocity/zenlib/pull/51. This PR is not from a forked repo ([explanation](https://github.com/reciprocity/zenlib/pull/51#issuecomment-573001656)).

feat: dropdown multiselect component

---

packages/_bootstrap_/scss/custom.scss
packages/_bootstrap_/scss/overrides.scss

Setting header font size variables to match the [Design system](https://share.goabstract.com/7f49bfd9-7e25-4445-9811-480a31f5302f?collectionLayerId=940294b0-5202-4c38-8e93-09cf7cdace90&mode=build)

Header sizes

---

README.md
package.json
packages/_storybook_/package.json
packages/_storybook_/stories/DaterPicker.stories.js
packages/date-picker/DatePicker.spec.js
packages/date-picker/DatePicker.vue
packages/date-picker/README.md
packages/date-picker/datepicker.scss
packages/date-picker/index.js
packages/date-picker/package-lock.json
packages/date-picker/package.json

[Jira ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-14030)

ZEN-14030: Add date-picker

---

packages/_storybook_/package-lock.json
packages/date-picker/package-lock.json
packages/dropdown-multiselect/package-lock.json
packages/multiselect/Multiselect.vue

[Jira ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-13939)

ZEN-13939: Restrict multiselect component to display options in one line

---

packages/_storybook_/stories/DaterPicker.stories.js
packages/date-picker/datepicker.scss
packages/date-picker/package.json

https://reciprocitylabs.atlassian.net/browse/ZEN-14167

ZEN-14167: Change date-picker styles

---

packages/date-picker/DatePicker.vue

https://reciprocitylabs.atlassian.net/browse/ZEN-14231

ZEN-14231 Add disabled date-picker prop support and styles

---

packages/_storybook_/stories/components/Button.stories.js
packages/_storybook_/stories/components/DaterPicker.stories.js
packages/date-picker/DatePicker.vue

https://reciprocitylabs.atlassian.net/browse/ZEN-14665
- Overwrites some popup DatePicker styles
- Adds a couple DatePicker stories

feat: adds styling to DatePicker

---

packages/_storybook_/stories/global/colors/README.md

Added small example of how to import scss files into Javascript.

docs: add export doc

---

packages/_bootstrap_/package-lock.json
packages/_bootstrap_/scss/variables.scss
packages/color-input/ColorInput.spec.js

As per jira ticket:
https://reciprocitylabs.atlassian.net/browse/ZEN-13232

ZEN-13232: Status colors dictionary

---

packages/dropdown-multiselect/DropdownMultiselect.spec.js
packages/dropdown-multiselect/DropdownMultiselect.vue
packages/multiselect/Multiselect.vue

As per jira ticket:
https://reciprocitylabs.atlassian.net/browse/ZEN-15065

ZEN-15065: Zen multiselect - Show counter when multiple selected SECOND PART

---

.github/CODEOWNERS
packages/multiselect/package-lock.json

Adding `@frontenders` team codeowners to promote PR reviews.

Adding @frontenders as codeowners

---

packages/multiselect/Multiselect.vue
packages/multiselect/package-lock.json

Remove new-flag and colorize dropdowns, so it can be tested on https://jan.dev.zengrc.com/

ZEN-15065: Zen multiselect - Show counter when multiple selected THIRD PART

---

packages/multiselect/Multiselect.vue

ZEN-15065: Zen multiselect - Show counter when multiple selected FOURTH PART

---

README.md

Reopening #73 
I'm sorry for the confusion. I accidentally deleted remote branch and ci apparently can't continue on restored branches. All your comments from #73 are fixed now.

Quickfix-update-readme-2

---

package-lock.json
package.json
packages/_storybook_/package-lock.json
packages/_storybook_/stories/components/Multiselect.stories.js
packages/multiselect/Multiselect.vue
packages/multiselect/package-lock.json
packages/multiselect/package.json

- Replace vue-multiselect with our fork.
- Search in a dropdown for multi-selects

ZEN-15065: Zen multiselect - Show counter when multiple selected FIFTH PART

---

packages/multiselect/Multiselect.vue

ZEN-15065: Zen multiselect - Show counter when multiple selected SIXTH PART

---

package-lock.json
package.json
packages/_storybook_/package-lock.json
packages/multiselect/Multiselect.vue
packages/multiselect/package-lock.json
packages/multiselect/package.json

Fix commit hashes for vue-multiselect fork so that right version gets picked up.

ZEN-15065: Zen multiselect improvements SEVENTH debug PART

---

packages/multiselect/Multiselect.vue

ZEN-15065: Zen multiselect - Show counter when multiple selected SEVENTH PART

---

packages/tags/Tags.vue
packages/tags/package-lock.json

`@reciprocity/bootstrap/scss/functions` doesn't exist.

fix: broken Tags component dependency

---

package-lock.json
package.json
packages/_storybook_/package-lock.json
packages/_storybook_/package.json
packages/_storybook_/stories/components/Multiselect.stories.js
packages/multiselect/package-lock.json
packages/multiselect/package.json

As per [Jira ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-15568)

ZEN-15568: Dropdown - Exception if not searchable

---

packages/_storybook_/package-lock.json
packages/multiselect/Multiselect.spec.js
packages/multiselect/Multiselect.vue

Description in [jira ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-16479)

ZEN-16479: X deselect on ZenMultiselect sets empty string instead of empty value

---

packages/file-dropzone/FileDropzone.vue
packages/file-dropzone/package-lock.json
packages/file-dropzone/package.json

As requested by Igor, I've changed the design of FileDropzone.
Check jira:
https://reciprocitylabs.atlassian.net/browse/ZEN-17164

ZEN-17164: Redesign FileDropzone

---

README.md
package.json
packages/multiselect-custom-el-poc/Multiselect.spec.js
packages/multiselect-custom-el-poc/Multiselect.vue
packages/multiselect-custom-el-poc/README.md
packages/multiselect-custom-el-poc/index.js
packages/multiselect-custom-el-poc/package-lock.json
packages/multiselect-custom-el-poc/package.json
packages/multiselect-custom-el-poc/webComponentHelper.js
packages/multiselect-custom-el-poc/webComponentHelper.spec.js

Export zen-multiselect as a standard web component to be used in Micro frontends POC (Risk assessment).
A new component was made because it's just a POC and to make sure it doesn't affect the original multiselect in any way.

POC: Add Mutiselect custom element
